fragment SiteSettingsParts on SiteSettings {
  __typename
  name
  description
  url
  contactEmail
  ogImage
}

fragment NavigationParts on Navigation {
  __typename
  primary {
    __typename
    label
    url
  }
  cta {
    __typename
    label
    url
  }
}

fragment HomepageParts on Homepage {
  __typename
  blocks {
    __typename
    ... on HomepageBlocksHero {
      sectionLabel
      headline
      body
      image
      imageAlt
      ctaLabel
      ctaUrl
      annotation
    }
    ... on HomepageBlocksFeatured_event {
      sectionLabel
      event
    }
    ... on HomepageBlocksPillar_grid {
      sectionLabel
      items {
        __typename
        title
        body
        url
        folio
      }
    }
    ... on HomepageBlocksManifesto {
      sectionLabel
      text
      accent
    }
  }
}

fragment EventsParts on Events {
  __typename
  title
  subtitle
  date
  time
  venue
  city
  ticketUrl
  image
  imageAlt
  description
  catalogNumber
  body
}

fragment JournalParts on Journal {
  __typename
  title
  dek
  date
  author
  image
  imageAlt
  body
}

fragment ArchiveParts on Archive {
  __typename
  title
  description
  image
  imageAlt
  body
}

fragment PublishingParts on Publishing {
  __typename
  title
  description
  image
  imageAlt
  body
}

fragment PeopleParts on People {
  __typename
  title
  description
  image
  imageAlt
  body
}
