//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  navigation: Navigation;
  navigationConnection: NavigationConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  events: Events;
  eventsConnection: EventsConnection;
  journal: Journal;
  journalConnection: JournalConnection;
  archive: Archive;
  archiveConnection: ArchiveConnection;
  publishing: Publishing;
  publishingConnection: PublishingConnection;
  people: People;
  peopleConnection: PeopleConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryNavigationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavigationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavigationFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};


export type QueryJournalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJournalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
};


export type QueryArchiveArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArchiveConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArchiveFilter>;
};


export type QueryPublishingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPublishingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublishingFilter>;
};


export type QueryPeopleArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPeopleConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeopleFilter>;
};

export type DocumentFilter = {
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  navigation?: InputMaybe<NavigationFilter>;
  homepage?: InputMaybe<HomepageFilter>;
  events?: InputMaybe<EventsFilter>;
  journal?: InputMaybe<JournalFilter>;
  archive?: InputMaybe<ArchiveFilter>;
  publishing?: InputMaybe<PublishingFilter>;
  people?: InputMaybe<PeopleFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteSettings | Navigation | Homepage | Events | Journal | Archive | Publishing | People | Folder;

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  name: Scalars['String']['output'];
  description: Scalars['String']['output'];
  url: Scalars['String']['output'];
  contactEmail: Scalars['String']['output'];
  ogImage?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSettingsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  contactEmail?: InputMaybe<StringFilter>;
  ogImage?: InputMaybe<ImageFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type NavigationPrimary = {
  __typename?: 'NavigationPrimary';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type NavigationCta = {
  __typename?: 'NavigationCta';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type Navigation = Node & Document & {
  __typename?: 'Navigation';
  primary?: Maybe<Array<Maybe<NavigationPrimary>>>;
  cta?: Maybe<NavigationCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavigationPrimaryFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type NavigationCtaFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type NavigationFilter = {
  primary?: InputMaybe<NavigationPrimaryFilter>;
  cta?: InputMaybe<NavigationCtaFilter>;
};

export type NavigationConnectionEdges = {
  __typename?: 'NavigationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Navigation>;
};

export type NavigationConnection = Connection & {
  __typename?: 'NavigationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavigationConnectionEdges>>>;
};

export type HomepageBlocksHero = {
  __typename?: 'HomepageBlocksHero';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  headline: Scalars['String']['output'];
  body?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaUrl?: Maybe<Scalars['String']['output']>;
  annotation?: Maybe<Scalars['String']['output']>;
};

export type HomepageBlocksFeatured_Event = {
  __typename?: 'HomepageBlocksFeatured_event';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  event?: Maybe<Scalars['String']['output']>;
};

export type HomepageBlocksPillar_GridItems = {
  __typename?: 'HomepageBlocksPillar_gridItems';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  folio?: Maybe<Scalars['String']['output']>;
};

export type HomepageBlocksPillar_Grid = {
  __typename?: 'HomepageBlocksPillar_grid';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomepageBlocksPillar_GridItems>>>;
};

export type HomepageBlocksManifesto = {
  __typename?: 'HomepageBlocksManifesto';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  accent?: Maybe<Scalars['String']['output']>;
};

export type HomepageBlocks = HomepageBlocksHero | HomepageBlocksFeatured_Event | HomepageBlocksPillar_Grid | HomepageBlocksManifesto;

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  blocks?: Maybe<Array<Maybe<HomepageBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageBlocksHeroFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaUrl?: InputMaybe<StringFilter>;
  annotation?: InputMaybe<StringFilter>;
};

export type HomepageBlocksFeatured_EventFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  event?: InputMaybe<StringFilter>;
};

export type HomepageBlocksPillar_GridItemsFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  folio?: InputMaybe<StringFilter>;
};

export type HomepageBlocksPillar_GridFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomepageBlocksPillar_GridItemsFilter>;
};

export type HomepageBlocksManifestoFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  accent?: InputMaybe<StringFilter>;
};

export type HomepageBlocksFilter = {
  hero?: InputMaybe<HomepageBlocksHeroFilter>;
  featured_event?: InputMaybe<HomepageBlocksFeatured_EventFilter>;
  pillar_grid?: InputMaybe<HomepageBlocksPillar_GridFilter>;
  manifesto?: InputMaybe<HomepageBlocksManifestoFilter>;
};

export type HomepageFilter = {
  blocks?: InputMaybe<HomepageBlocksFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  time?: Maybe<Scalars['String']['output']>;
  venue?: Maybe<Scalars['String']['output']>;
  city?: Maybe<Scalars['String']['output']>;
  ticketUrl?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  catalogNumber?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventsFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  ticketUrl?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  catalogNumber?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Journal = Node & Document & {
  __typename?: 'Journal';
  title: Scalars['String']['output'];
  dek?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type JournalFilter = {
  title?: InputMaybe<StringFilter>;
  dek?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type JournalConnectionEdges = {
  __typename?: 'JournalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Journal>;
};

export type JournalConnection = Connection & {
  __typename?: 'JournalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<JournalConnectionEdges>>>;
};

export type Archive = Node & Document & {
  __typename?: 'Archive';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ArchiveFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArchiveConnectionEdges = {
  __typename?: 'ArchiveConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Archive>;
};

export type ArchiveConnection = Connection & {
  __typename?: 'ArchiveConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArchiveConnectionEdges>>>;
};

export type Publishing = Node & Document & {
  __typename?: 'Publishing';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PublishingFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PublishingConnectionEdges = {
  __typename?: 'PublishingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Publishing>;
};

export type PublishingConnection = Connection & {
  __typename?: 'PublishingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PublishingConnectionEdges>>>;
};

export type People = Node & Document & {
  __typename?: 'People';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PeopleFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PeopleConnectionEdges = {
  __typename?: 'PeopleConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<People>;
};

export type PeopleConnection = Connection & {
  __typename?: 'PeopleConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PeopleConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updateNavigation: Navigation;
  createNavigation: Navigation;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateEvents: Events;
  createEvents: Events;
  updateJournal: Journal;
  createJournal: Journal;
  updateArchive: Archive;
  createArchive: Archive;
  updatePublishing: Publishing;
  createPublishing: Publishing;
  updatePeople: People;
  createPeople: People;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdateNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: NavigationMutation;
};


export type MutationCreateNavigationArgs = {
  relativePath: Scalars['String']['input'];
  params: NavigationMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationUpdateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationCreateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationUpdateArchiveArgs = {
  relativePath: Scalars['String']['input'];
  params: ArchiveMutation;
};


export type MutationCreateArchiveArgs = {
  relativePath: Scalars['String']['input'];
  params: ArchiveMutation;
};


export type MutationUpdatePublishingArgs = {
  relativePath: Scalars['String']['input'];
  params: PublishingMutation;
};


export type MutationCreatePublishingArgs = {
  relativePath: Scalars['String']['input'];
  params: PublishingMutation;
};


export type MutationUpdatePeopleArgs = {
  relativePath: Scalars['String']['input'];
  params: PeopleMutation;
};


export type MutationCreatePeopleArgs = {
  relativePath: Scalars['String']['input'];
  params: PeopleMutation;
};

export type DocumentUpdateMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  navigation?: InputMaybe<NavigationMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  events?: InputMaybe<EventsMutation>;
  journal?: InputMaybe<JournalMutation>;
  archive?: InputMaybe<ArchiveMutation>;
  publishing?: InputMaybe<PublishingMutation>;
  people?: InputMaybe<PeopleMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  navigation?: InputMaybe<NavigationMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  events?: InputMaybe<EventsMutation>;
  journal?: InputMaybe<JournalMutation>;
  archive?: InputMaybe<ArchiveMutation>;
  publishing?: InputMaybe<PublishingMutation>;
  people?: InputMaybe<PeopleMutation>;
};

export type SiteSettingsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  contactEmail?: InputMaybe<Scalars['String']['input']>;
  ogImage?: InputMaybe<Scalars['String']['input']>;
};

export type NavigationPrimaryMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type NavigationCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type NavigationMutation = {
  primary?: InputMaybe<Array<InputMaybe<NavigationPrimaryMutation>>>;
  cta?: InputMaybe<NavigationCtaMutation>;
};

export type HomepageBlocksHeroMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaUrl?: InputMaybe<Scalars['String']['input']>;
  annotation?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageBlocksFeatured_EventMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  event?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageBlocksPillar_GridItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  folio?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageBlocksPillar_GridMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomepageBlocksPillar_GridItemsMutation>>>;
};

export type HomepageBlocksManifestoMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  accent?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageBlocksMutation = {
  hero?: InputMaybe<HomepageBlocksHeroMutation>;
  featured_event?: InputMaybe<HomepageBlocksFeatured_EventMutation>;
  pillar_grid?: InputMaybe<HomepageBlocksPillar_GridMutation>;
  manifesto?: InputMaybe<HomepageBlocksManifestoMutation>;
};

export type HomepageMutation = {
  blocks?: InputMaybe<Array<InputMaybe<HomepageBlocksMutation>>>;
};

export type EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  ticketUrl?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  catalogNumber?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type JournalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  dek?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArchiveMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PublishingMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PeopleMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', name: string, description: string, url: string, contactEmail: string, ogImage?: string | null };

export type NavigationPartsFragment = { __typename: 'Navigation', primary?: Array<{ __typename: 'NavigationPrimary', label: string, url: string } | null> | null, cta?: { __typename: 'NavigationCta', label: string, url: string } | null };

export type HomepagePartsFragment = { __typename: 'Homepage', blocks?: Array<{ __typename: 'HomepageBlocksHero', sectionLabel?: string | null, headline: string, body?: string | null, image?: string | null, imageAlt?: string | null, ctaLabel?: string | null, ctaUrl?: string | null, annotation?: string | null } | { __typename: 'HomepageBlocksFeatured_event', sectionLabel?: string | null, event?: string | null } | { __typename: 'HomepageBlocksPillar_grid', sectionLabel?: string | null, items?: Array<{ __typename: 'HomepageBlocksPillar_gridItems', title?: string | null, body?: string | null, url?: string | null, folio?: string | null } | null> | null } | { __typename: 'HomepageBlocksManifesto', sectionLabel?: string | null, text?: string | null, accent?: string | null } | null> | null };

export type EventsPartsFragment = { __typename: 'Events', title: string, subtitle?: string | null, date?: string | null, time?: string | null, venue?: string | null, city?: string | null, ticketUrl?: string | null, image?: string | null, imageAlt?: string | null, description?: string | null, catalogNumber?: string | null, body?: any | null };

export type JournalPartsFragment = { __typename: 'Journal', title: string, dek?: string | null, date?: string | null, author?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null };

export type ArchivePartsFragment = { __typename: 'Archive', title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null };

export type PublishingPartsFragment = { __typename: 'Publishing', title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null };

export type PeoplePartsFragment = { __typename: 'People', title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, name: string, description: string, url: string, contactEmail: string, ogImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, name: string, description: string, url: string, contactEmail: string, ogImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NavigationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavigationQuery = { __typename?: 'Query', navigation: { __typename: 'Navigation', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, primary?: Array<{ __typename: 'NavigationPrimary', label: string, url: string } | null> | null, cta?: { __typename: 'NavigationCta', label: string, url: string } | null } };

export type NavigationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavigationFilter>;
}>;


export type NavigationConnectionQuery = { __typename?: 'Query', navigationConnection: { __typename?: 'NavigationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavigationConnectionEdges', cursor: string, node?: { __typename: 'Navigation', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, primary?: Array<{ __typename: 'NavigationPrimary', label: string, url: string } | null> | null, cta?: { __typename: 'NavigationCta', label: string, url: string } | null } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'HomepageBlocksHero', sectionLabel?: string | null, headline: string, body?: string | null, image?: string | null, imageAlt?: string | null, ctaLabel?: string | null, ctaUrl?: string | null, annotation?: string | null } | { __typename: 'HomepageBlocksFeatured_event', sectionLabel?: string | null, event?: string | null } | { __typename: 'HomepageBlocksPillar_grid', sectionLabel?: string | null, items?: Array<{ __typename: 'HomepageBlocksPillar_gridItems', title?: string | null, body?: string | null, url?: string | null, folio?: string | null } | null> | null } | { __typename: 'HomepageBlocksManifesto', sectionLabel?: string | null, text?: string | null, accent?: string | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'HomepageBlocksHero', sectionLabel?: string | null, headline: string, body?: string | null, image?: string | null, imageAlt?: string | null, ctaLabel?: string | null, ctaUrl?: string | null, annotation?: string | null } | { __typename: 'HomepageBlocksFeatured_event', sectionLabel?: string | null, event?: string | null } | { __typename: 'HomepageBlocksPillar_grid', sectionLabel?: string | null, items?: Array<{ __typename: 'HomepageBlocksPillar_gridItems', title?: string | null, body?: string | null, url?: string | null, folio?: string | null } | null> | null } | { __typename: 'HomepageBlocksManifesto', sectionLabel?: string | null, text?: string | null, accent?: string | null } | null> | null } | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventsQuery = { __typename?: 'Query', events: { __typename: 'Events', id: string, title: string, subtitle?: string | null, date?: string | null, time?: string | null, venue?: string | null, city?: string | null, ticketUrl?: string | null, image?: string | null, imageAlt?: string | null, description?: string | null, catalogNumber?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
}>;


export type EventsConnectionQuery = { __typename?: 'Query', eventsConnection: { __typename?: 'EventsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventsConnectionEdges', cursor: string, node?: { __typename: 'Events', id: string, title: string, subtitle?: string | null, date?: string | null, time?: string | null, venue?: string | null, city?: string | null, ticketUrl?: string | null, image?: string | null, imageAlt?: string | null, description?: string | null, catalogNumber?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type JournalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type JournalQuery = { __typename?: 'Query', journal: { __typename: 'Journal', id: string, title: string, dek?: string | null, date?: string | null, author?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type JournalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
}>;


export type JournalConnectionQuery = { __typename?: 'Query', journalConnection: { __typename?: 'JournalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'JournalConnectionEdges', cursor: string, node?: { __typename: 'Journal', id: string, title: string, dek?: string | null, date?: string | null, author?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ArchiveQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArchiveQuery = { __typename?: 'Query', archive: { __typename: 'Archive', id: string, title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArchiveConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArchiveFilter>;
}>;


export type ArchiveConnectionQuery = { __typename?: 'Query', archiveConnection: { __typename?: 'ArchiveConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArchiveConnectionEdges', cursor: string, node?: { __typename: 'Archive', id: string, title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PublishingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PublishingQuery = { __typename?: 'Query', publishing: { __typename: 'Publishing', id: string, title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PublishingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublishingFilter>;
}>;


export type PublishingConnectionQuery = { __typename?: 'Query', publishingConnection: { __typename?: 'PublishingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PublishingConnectionEdges', cursor: string, node?: { __typename: 'Publishing', id: string, title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PeopleQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PeopleQuery = { __typename?: 'Query', people: { __typename: 'People', id: string, title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PeopleConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeopleFilter>;
}>;


export type PeopleConnectionQuery = { __typename?: 'Query', peopleConnection: { __typename?: 'PeopleConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PeopleConnectionEdges', cursor: string, node?: { __typename: 'People', id: string, title: string, description?: string | null, image?: string | null, imageAlt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  name
  description
  url
  contactEmail
  ogImage
}
    `;
export const NavigationPartsFragmentDoc = gql`
    fragment NavigationParts on Navigation {
  __typename
  primary {
    __typename
    label
    url
  }
  cta {
    __typename
    label
    url
  }
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  blocks {
    __typename
    ... on HomepageBlocksHero {
      sectionLabel
      headline
      body
      image
      imageAlt
      ctaLabel
      ctaUrl
      annotation
    }
    ... on HomepageBlocksFeatured_event {
      sectionLabel
      event
    }
    ... on HomepageBlocksPillar_grid {
      sectionLabel
      items {
        __typename
        title
        body
        url
        folio
      }
    }
    ... on HomepageBlocksManifesto {
      sectionLabel
      text
      accent
    }
  }
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  title
  subtitle
  date
  time
  venue
  city
  ticketUrl
  image
  imageAlt
  description
  catalogNumber
  body
}
    `;
export const JournalPartsFragmentDoc = gql`
    fragment JournalParts on Journal {
  __typename
  title
  dek
  date
  author
  image
  imageAlt
  body
}
    `;
export const ArchivePartsFragmentDoc = gql`
    fragment ArchiveParts on Archive {
  __typename
  title
  description
  image
  imageAlt
  body
}
    `;
export const PublishingPartsFragmentDoc = gql`
    fragment PublishingParts on Publishing {
  __typename
  title
  description
  image
  imageAlt
  body
}
    `;
export const PeoplePartsFragmentDoc = gql`
    fragment PeopleParts on People {
  __typename
  title
  description
  image
  imageAlt
  body
}
    `;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const NavigationDocument = gql`
    query navigation($relativePath: String!) {
  navigation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavigationParts
  }
}
    ${NavigationPartsFragmentDoc}`;
export const NavigationConnectionDocument = gql`
    query navigationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavigationFilter) {
  navigationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavigationParts
      }
    }
  }
}
    ${NavigationPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export const JournalDocument = gql`
    query journal($relativePath: String!) {
  journal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...JournalParts
  }
}
    ${JournalPartsFragmentDoc}`;
export const JournalConnectionDocument = gql`
    query journalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: JournalFilter) {
  journalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...JournalParts
      }
    }
  }
}
    ${JournalPartsFragmentDoc}`;
export const ArchiveDocument = gql`
    query archive($relativePath: String!) {
  archive(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArchiveParts
  }
}
    ${ArchivePartsFragmentDoc}`;
export const ArchiveConnectionDocument = gql`
    query archiveConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArchiveFilter) {
  archiveConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArchiveParts
      }
    }
  }
}
    ${ArchivePartsFragmentDoc}`;
export const PublishingDocument = gql`
    query publishing($relativePath: String!) {
  publishing(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PublishingParts
  }
}
    ${PublishingPartsFragmentDoc}`;
export const PublishingConnectionDocument = gql`
    query publishingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PublishingFilter) {
  publishingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PublishingParts
      }
    }
  }
}
    ${PublishingPartsFragmentDoc}`;
export const PeopleDocument = gql`
    query people($relativePath: String!) {
  people(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PeopleParts
  }
}
    ${PeoplePartsFragmentDoc}`;
export const PeopleConnectionDocument = gql`
    query peopleConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PeopleFilter) {
  peopleConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PeopleParts
      }
    }
  }
}
    ${PeoplePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    navigation(variables: NavigationQueryVariables, options?: C): Promise<{data: NavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationQueryVariables, query: string}> {
        return requester<{data: NavigationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationQueryVariables, query: string}, NavigationQueryVariables>(NavigationDocument, variables, options);
      },
    navigationConnection(variables?: NavigationConnectionQueryVariables, options?: C): Promise<{data: NavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationConnectionQueryVariables, query: string}> {
        return requester<{data: NavigationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavigationConnectionQueryVariables, query: string}, NavigationConnectionQueryVariables>(NavigationConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      },
    journal(variables: JournalQueryVariables, options?: C): Promise<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}> {
        return requester<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}, JournalQueryVariables>(JournalDocument, variables, options);
      },
    journalConnection(variables?: JournalConnectionQueryVariables, options?: C): Promise<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}> {
        return requester<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}, JournalConnectionQueryVariables>(JournalConnectionDocument, variables, options);
      },
    archive(variables: ArchiveQueryVariables, options?: C): Promise<{data: ArchiveQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArchiveQueryVariables, query: string}> {
        return requester<{data: ArchiveQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArchiveQueryVariables, query: string}, ArchiveQueryVariables>(ArchiveDocument, variables, options);
      },
    archiveConnection(variables?: ArchiveConnectionQueryVariables, options?: C): Promise<{data: ArchiveConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArchiveConnectionQueryVariables, query: string}> {
        return requester<{data: ArchiveConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArchiveConnectionQueryVariables, query: string}, ArchiveConnectionQueryVariables>(ArchiveConnectionDocument, variables, options);
      },
    publishing(variables: PublishingQueryVariables, options?: C): Promise<{data: PublishingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublishingQueryVariables, query: string}> {
        return requester<{data: PublishingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublishingQueryVariables, query: string}, PublishingQueryVariables>(PublishingDocument, variables, options);
      },
    publishingConnection(variables?: PublishingConnectionQueryVariables, options?: C): Promise<{data: PublishingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublishingConnectionQueryVariables, query: string}> {
        return requester<{data: PublishingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublishingConnectionQueryVariables, query: string}, PublishingConnectionQueryVariables>(PublishingConnectionDocument, variables, options);
      },
    people(variables: PeopleQueryVariables, options?: C): Promise<{data: PeopleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleQueryVariables, query: string}> {
        return requester<{data: PeopleQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleQueryVariables, query: string}, PeopleQueryVariables>(PeopleDocument, variables, options);
      },
    peopleConnection(variables?: PeopleConnectionQueryVariables, options?: C): Promise<{data: PeopleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleConnectionQueryVariables, query: string}> {
        return requester<{data: PeopleConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeopleConnectionQueryVariables, query: string}, PeopleConnectionQueryVariables>(PeopleConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/v1/content/060390f4-a119-4728-a1b0-4b36558ce1f8/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  